import Deck from '@/deck/Deck';
import Slide from '@/deck/Slide';
import './midsem.css';

type Evidence = { image: string; caption: string; source: string; page: string; href: string };
type Item = { section: string; title: string; lead: string; points: string[]; notes: string; evidence?: Evidence[]; kind?: 'cover' | 'statement' | 'flow' | 'final' };

const b = (image: string, caption: string, page: string): Evidence => ({ image, caption, source: 'Laperdrix et al. · IEEE S&P 2016', page, href: '/papers/beauty-sp16.pdf' });
const n = (image: string, caption: string, page: string): Evidence => ({ image, caption, source: 'Cao, Li & Wijmans · NDSS 2017', page, href: '/papers/ndss2017_02B-3_Cao_paper.pdf' });
const t = (image: string, caption: string, page: string): Evidence => ({ image, caption, source: 'Browser fingerprinting technical report · 2025', page, href: '/papers/techreport-2025-3.pdf' });

const slides: Item[] = [
  {kind:'cover',section:'MIDSEM RESEARCH PRESENTATION · 2026',title:'VPN detection through evidence',lead:'A website-based study of network observations, browser fingerprinting, and explainable assessment.',points:['Research project','Use ← → to navigate · P for presenter notes'],notes:'Our question is whether website-visible network and browser evidence can identify VPN-compatible visits, and with what error rate.'},
  {kind:'statement',section:'Introduction',title:'One visit gives us two views',lead:'The server observes a connection. The browser exposes selected environment details when a scan runs.',points:['Server: ingress IP and request context','Browser: system and rendering attributes'],evidence:[b('beauty-table','Table I · HTTP and JavaScript sources','4')],notes:'The paper shows which attributes can be collected from HTTP and JavaScript.'},
  {section:'Motivation',title:'An IP address is not the whole story',lead:'A route may change while the device stays the same.',points:['Dynamic allocation, mobile access, and location changes can change an IP address.','Fingerprint signals add continuity across visits, but continuity does not prove VPN use.'],evidence:[n('ndss-abstract','NDSS studies recognition across browsers','1')],notes:'IP change is ambiguous. NDSS provides device continuity methods, not VPN detection accuracy.'},
  {kind:'statement',section:'Research problem',title:'How can we flag VPN-compatible visits without treating every mismatch as proof?',lead:'We need trusted observations, an explanation for each flag, and a way to say “insufficient evidence.”',points:['Observe','Compare','Validate'],notes:'This is our research problem, not a result claimed by a paper.'},
  {kind:'flow',section:'Literature review',title:'Three papers, three distinct questions',lead:'Each paper answers a different part of our research setup.',points:['Beauty and the Beast · Which browser attributes distinguish visitors?','NDSS 2017 · Which device features persist across browsers?','2025 technical report · How is fingerprinting detected on websites?'],notes:'None of these three papers evaluates our VPN detector.'},
  {section:'Literature review · Beauty',title:'What a browser fingerprint contains',lead:'The 2016 study collected 118,934 fingerprints across 17 attributes.',points:['HTTP headers and JavaScript expose different parts of the environment.','Canvas, platform, screen, and WebGL appear in the inventory.','Flash-based fields belong to the historical study, not our current app.'],evidence:[b('beauty-table','Table I · attribute sources and diversity','2–4')],notes:'Point to the Source column. Distinguish historical Flash fields from current browser capabilities.'},
  {section:'Literature review · Beauty',title:'Canvas exposes rendering differences',lead:'Fixed drawing instructions can produce distinguishing outputs.',points:['The paper draws text, colors, and an emoji to probe the graphics and font stack.','A rendering hash helps compare visits; it is not direct VPN evidence.'],evidence:[b('beauty-canvas','Figure 1 · the paper’s canvas test','6')],notes:'Describe the controlled canvas drawing. Avoid saying that canvas identifies a VPN.'},
  {section:'Literature review · NDSS',title:'Look below the browser layer',lead:'NDSS uses tasks that depend on the OS and hardware.',points:['Graphics, CPU, display, audio, and writing systems can aid cross-browser comparison.','Browser-dependent outputs must be separated from more stable device signals.'],evidence:[n('ndss-abstract','NDSS abstract · cross-browser fingerprinting','1'),n('ndss-browser-factor','Browser and device contributions differ','2')],notes:'Explain why our app has browser and coarse-device signatures.'},
  {section:'Literature review · NDSS',title:'Stability needs deliberate choices',lead:'A feature that changes between browsers is a poor cross-browser anchor.',points:['The paper shows screen resolution can change with zoom.','It also reports browser-dependent image representation.','Missing or unstable components need cautious treatment.'],evidence:[n('ndss-zoom','Screen values can vary with zoom','2'),n('ndss-png','DataURL and JPEG varied across browsers','2')],notes:'These are findings in the paper’s tested browsers, not a promise that our implementation solves every variation.'},
  {section:'Literature review · NDSS',title:'The NDSS result — and its boundary',lead:'Cross-browser recognition was measurable in the authors’ dataset.',points:['83.24% cross-browser uniqueness','91.44% cross-browser stability','These are fingerprinting results, not VPN detection accuracy.'],evidence:[n('ndss-results','Table II · results on the NDSS dataset','9'),n('ndss-stability-b','Meaning of cross-browser stability','9')],notes:'Never present these percentages as our VPN detection accuracy.'},
  {section:'Literature review · Technical report',title:'This report studies fingerprinting scripts',lead:'Its target is website fingerprinting behavior, not VPN use.',points:['The report separates critical and generic browser attribute groups.','Its heuristic uses observed APIs and thresholds to infer fingerprinting behavior.'],evidence:[t('tech-classes','Table 5 · attribute groups','39'),t('tech-algorithm','Figure 11 · decision rule','41')],notes:'This paper detects fingerprinting scripts deployed by websites, not VPN users.'},
  {section:'Literature review · Technical report',title:'A method changes what gets counted',lead:'Two methods in the report produced different estimates.',points:['List-based classification found fingerprinting scripts on 38.55% of studied sites.','FPAnalyze reported 33.57% under its heuristic method.','Our VPN rules also require labelled validation.'],evidence:[t('tech-prevalence','List-based measurement · 38.55%','50'),t('tech-fpanalyze','Heuristic measurement · 33.57%','53')],notes:'These percentages are fingerprinting prevalence, not VPN prevalence.'},
  {kind:'statement',section:'Research gap',title:'Browser recognition does not equal VPN detection',lead:'The literature gives us comparison methods. We must test whether adding network evidence improves VPN assessment.',points:['Browser evidence','+ network evidence','→ labelled VPN evaluation'],notes:'The gap is our synthesis. The supplied papers do not test our proposed combination.'},
  {kind:'statement',section:'Problem statement',title:'Can website-visible evidence identify VPN-compatible sessions with measured error rates?',lead:'The output is an explained assessment, not proof of a person’s location or identity.',points:[],notes:'State the research question. No result is claimed yet.'},
  {kind:'flow',section:'Objectives',title:'Build the instrument, then measure it',lead:'Four objectives for the midsem project.',points:['01 · Collect disclosed browser and trusted server observations.','02 · Compare same-device and cross-browser visits.','03 · Explain the evidence behind each flag.','04 · Evaluate with labelled VPN-on and VPN-off sessions.'],notes:'The first three objectives are implementation; the fourth tests the research claim.'},
  {kind:'flow',section:'Proposed framework',title:'Two calculations, one evidence report',lead:'Device continuity and VPN risk answer different questions.',points:['01 · Browser collection: environment and rendering attributes','02 · Device similarity: compare available components','03 · Network evidence: ingress IP, classification, optional path probes','04 · VPN assessment: explain signals and uncertainty'],notes:'A matching fingerprint is continuity context, not proof of VPN use.'},
  {section:'Implemented algorithm',title:'How we form a fingerprint',lead:'Collect → normalize → serialize → hash',points:['Inputs: browser, OS, hardware buckets, display, canvas, WebGL, fonts, and capabilities.','Optional opt-in NDSS tasks add fixed rendering and system outputs.','SHA-256 creates browser and coarse-device signatures. A hash is not a VPN verdict.'],evidence:[b('beauty-table','Research basis for collecting multiple attributes','4')],notes:'The app creates separate browser and coarse-device signatures from selected fields.'},
  {section:'Implemented algorithm',title:'Why factors have different roles',lead:'Cross-browser matching favors device features; same-browser matching can use browser outputs.',points:['Similarity = Σ(weight × agreement) ÷ Σ(available weights).','OS and GPU family currently carry more weight than color gamut or pointer class.','The exact numeric weights are provisional; no cited paper supplies them.'],evidence:[n('ndss-browser-factor','NDSS distinguishes browser and device factors','2'),n('ndss-variation','Selected features can still vary','9')],notes:'The rank ordering has a research rationale. The exact weights require calibration on labelled pairs.'},
  {section:'Implemented algorithm',title:'Select NDSS-style tasks using labelled pairs',lead:'A task should agree on the same device and help separate different devices.',points:['Collect fixed graphics and system tasks when users opt in.','Keep tasks available across a browser pair.','Search a bounded set for stability × uniqueness.','Return no trained mask when labelled pairs are insufficient.'],evidence:[n('ndss-graphics','Graphics tasks can expose hardware variation','3–7')],notes:'This is an adapted bounded search, not a reproduction of the NDSS percentages.'},
  {kind:'flow',section:'Implemented algorithm',title:'VPN evidence starts with the network',lead:'The current risk score separates routing evidence from contextual clues.',points:['Stronger · Tor exit or VPN network classification; differing public WebRTC path','Moderate · trusted IPv4/IPv6 route differences; permissioned location','Weaker · timezone, device continuity after an IP change, browser integrity','All current numeric risk weights and the 5% prior remain uncalibrated.'],notes:'MaxMind and Tor lists refer to the observed connection. Fingerprint and timezone clues are context. Exact values need evaluation.'},
  {section:'Evaluation & conclusion',title:'The next result must come from labelled tests',lead:'We can present a prototype today; performance requires an experiment.',points:['Test VPN on/off, ordinary network changes, browser changes, and privacy modes.','Report precision, recall, false-positive rate, calibration, and abstentions.','Privacy protections may suppress browser signals; absence is not VPN evidence.'],evidence:[n('ndss-tor','Privacy browsers can suppress fingerprint features','13')],notes:'The papers justify measurement methods. Our next milestone is a labelled VPN evaluation.'},
  {kind:'final',section:'Project status',title:'What we have built',lead:'vpn-detector-final · consent-based VPN and device research website',points:['Capture: browser, rendering, server network, optional NDSS tasks','Compare: browser and coarse-device signatures with component explanations','Assess: network, path, location, history, and integrity evidence','Evaluate: stored observations and labelled performance metrics'],notes:'End on the built prototype. Optional integrations need configuration. Risk percentages are uncalibrated until tested.'},
];

function EvidencePanel({ item }: { item: Evidence }) {
  return <figure className="ms-proof"><div className="ms-proof-image"><img src={`/evidence/${item.image}.png`} alt={item.caption}/></div><figcaption>{item.caption}<a href={item.href} target="_blank" rel="noreferrer">{item.source} · PDF p. {item.page} ↗</a></figcaption></figure>;
}

function OneSlide({ item, index }: { item: Item; index: number; notes?: string }) {
  const number = String(index + 1).padStart(2, '0');
  if (item.kind === 'cover') return <Slide nav={item.title} notes={item.notes} className="ms-slide ms-cover"><div className="ms-cover-inner"><div className="ms-kicker">{item.section}</div><div className="ms-orbit" aria-hidden="true"><i/><i/><i/></div><h1>VPN detection<br/><em>through evidence</em></h1><p>{item.lead}</p><div className="ms-cover-bottom"><span>{item.points[0]}</span><span>{item.points[1]}</span></div></div></Slide>;
  return <Slide nav={item.title} notes={item.notes} className={`ms-slide ${item.kind === 'statement' ? 'ms-statement' : ''} ${item.kind === 'final' ? 'ms-final' : ''}`}><div className="ms-main"><header><div className="ms-kicker"><span>{number}</span><span className="ms-kicker-dot"/>{item.section}</div><h2>{item.title}</h2><p>{item.lead}</p></header><div className={item.evidence?.length ? 'ms-layout has-evidence' : 'ms-layout'}><div className="ms-points">{item.points.map((point, i) => <div className="ms-point" key={i}><span>{String(i + 1).padStart(2, '0')}</span><p>{point}</p></div>)}</div>{item.evidence && <div className={`ms-evidence ${item.evidence.length > 1 ? 'multiple' : ''}`}>{item.evidence.map((ev, i) => <EvidencePanel key={i} item={ev}/>)}</div>}</div>{item.kind === 'final' && <div className="ms-final-banner">Built prototype. Next milestone: calibrate and validate on representative labelled VPN traffic.</div>}{index === 19 && <div className="ms-extra-links"><a href="https://dev.maxmind.com/geoip/docs/databases/anonymous-plus/binary/" target="_blank" rel="noreferrer">MaxMind field definitions ↗</a><a href="https://datatracker.ietf.org/doc/rfc8828/" target="_blank" rel="noreferrer">RFC 8828 · WebRTC IP handling ↗</a></div>}{index === 17 && <div className="ms-extra-links"><a href="https://arxiv.org/pdf/2006.09511" target="_blank" rel="noreferrer">Additional study · distinctiveness and stability ↗</a><a href="https://arxiv.org/pdf/2403.15607" target="_blank" rel="noreferrer">Additional study · correlated attributes ↗</a></div>}</div></Slide>;
}

export default function Home() { return <Deck>{slides.map((item, index) => <OneSlide key={index} item={item} index={index} notes={item.notes} />)}</Deck>; }
