import Deck from '@/deck/Deck';
import Slide from '@/deck/Slide';
import './midsem.css';

type Evidence = { image: string; caption: string; source: string; page: number; href: string };
type PaperLink = { label: string; href: string };
type Item = { section: string; title: string; lead: string; points: string[]; notes: string; evidence?: Evidence[]; links?: PaperLink[]; kind?: 'cover' | 'statement' | 'flow' | 'final' };

const paper = (file: string, page: number) => '/papers/' + file + '#page=' + page;
const b = (image: string, caption: string, page: number): Evidence => ({ image, caption, source: 'Laperdrix et al. · 2016', page, href: paper('beauty-sp16.pdf', page) });
const n = (image: string, caption: string, page: number): Evidence => ({ image, caption, source: 'Cao, Li & Wijmans · 2017', page, href: paper('ndss2017_02B-3_Cao_paper.pdf', page) });
const t = (image: string, caption: string, page: number): Evidence => ({ image, caption, source: 'Chan King Sen · 2025', page, href: paper('techreport-2025-3.pdf', page) });
const s = (image: string, caption: string, page: number): Evidence => ({ image, caption, source: 'Schwartz et al. · SNITCH 2025', page, href: paper('snitch-madweb25.pdf', page) });
const m = (image: string, caption: string, page: number): Evidence => ({ image, caption, source: 'Mazel et al. · 2022', page, href: paper('tunnel-ml-2022.pdf', page) });

const slides: Item[] = [
  {kind:'cover',section:'MIDSEM RESEARCH PRESENTATION · 2026',title:'VPN detection through evidence',lead:'What research says, what our website does, and how we will test it.',points:['Research project','Use ← → to move · P for speaker notes'],notes:'We are building a website that studies VPN-related signals. This presentation first explains the research, then the steps in our prototype, then a plan for training and testing a model.'},
  {section:'Introduction + motivation',title:'Why do we need more than an IP address?',lead:'A VPN can change the route to a website. Other normal events can change it too.',points:['The website can see the connection that reaches its server.','Browser details can help tell whether two visits look like the same device.','We want to combine these clues and explain each decision.'],evidence:[s('snitch-abstract','Published server-side VPN detection',1)],notes:'Say that VPN detection is a real published research problem. SNITCH uses IP location and delay checks. Our website uses some related server and browser clues, so our own accuracy still needs testing.'},
  {kind:'flow',section:'Literature review',title:'Three papers give us three building blocks',lead:'Each paper answers one simple question.',points:['Beauty and the Beast: what browser details can we collect?','NDSS 2017: which device details stay useful across browsers?','2025 technical report: how do we score several clues and check the result?'],links:[{label:'Beauty · PDF page 2',href:paper('beauty-sp16.pdf',2)},{label:'NDSS · PDF page 1',href:paper('ndss2017_02B-3_Cao_paper.pdf',1)},{label:'Technical report · PDF page 38',href:paper('techreport-2025-3.pdf',38)}],notes:'Beauty is about browser fingerprints. NDSS is about cross-browser device fingerprints. The technical report is about detecting fingerprinting scripts on websites. We use their methods as building blocks.'},
  {section:'Paper 1 · Beauty and the Beast',title:'A fingerprint combines many browser details',lead:'The study collected 118,934 fingerprints made from 17 attributes.',points:['HTTP headers and JavaScript provide different fields.','Canvas, screen, platform and WebGL can help separate browsers.','Old Flash-based fields are historical; our site does not depend on Flash.'],evidence:[b('beauty-abstract-more','Abstract · sample size and canvas finding',2)],links:[{label:'See all 17 attributes · Table I page 4',href:paper('beauty-sp16.pdf',4)}],notes:'Point at the highlighted 118,934 and 17. Click the Table I link to show the full attribute list and its Source column. Explain that one field alone is weak; the combination makes the fingerprint.'},
  {section:'Paper 1 · Beauty and the Beast',title:'The test must give repeatable results',lead:'The paper shows both the value and the risk of graphics fingerprints.',points:['A fixed canvas drawing can reveal font and graphics differences.','An early WebGL test changed after a window resize.','So we keep task settings fixed and check the same device more than once.'],evidence:[b('beauty-canvas','Figure 1 · fixed canvas drawing',6),b('beauty-webgl-limit','The paper warns about a brittle WebGL test',4)],notes:'Explain canvas in plain words: the site asks the browser to draw the same picture, then compares the output. The paper also warns that a poorly controlled 3D test can change after resize. This is why repeatability matters.'},
  {section:'Paper 2 · NDSS 2017',title:'NDSS tests the device under the browser',lead:'The researchers used controlled graphics and system tasks.',points:['The browser runs the same task on each visit.','The output can reflect the OS, GPU, CPU and other device parts.','They used more than 20 carefully chosen graphics tasks.'],evidence:[n('ndss-abstract','Abstract · OS and hardware features',1),n('ndss-careful-tasks','More than 20 controlled WebGL tasks',2)],notes:'Contrast browser version with underlying hardware. A browser update may change browser fields, while some device features can remain. The study carefully fixed WebGL task settings.'},
  {section:'Paper 2 · NDSS 2017',title:'Some fields change even on the same device',lead:'We must check whether a field stays stable before trusting it.',points:['Zoom can change the screen value seen by a browser.','JPEG and DataURL outputs varied across browsers in the study.','Missing or changing fields should count less in a match.'],evidence:[n('ndss-zoom','Zoom can affect screen resolution',2),n('ndss-png','Some image outputs changed across browsers',2)],notes:'A useful field is both stable on the same device and different across devices. If a browser changes the field, it becomes a poor anchor for cross-browser matching.'},
  {section:'Paper 2 · NDSS 2017',title:'The paper measured cross-browser matching',lead:'Its results show why stability and uniqueness are separate tests.',points:['83.24% of cross-browser fingerprints were unique in its dataset.','91.44% stayed stable across browsers on the same machine.','These numbers describe that paper’s fingerprint test.'],evidence:[n('ndss-results','Table II · uniqueness and stability',9)],notes:'Read the cross-browser columns. Uniqueness asks whether the fingerprint separates machines. Stability asks whether it stays the same across browsers. We will measure both on our own samples.'},
  {section:'Paper 3 · 2025 technical report',title:'Several clues can be scored together',lead:'FPAnalyze looks for combinations of browser API use.',points:['It separates stronger “critical” groups from more common groups.','It checks several actions together instead of one action alone.','Its rule has clear thresholds that a reviewer can inspect.'],evidence:[t('tech-combined-heuristic','Section 4.4 · combined clues and thresholds',38),t('tech-classes','Table 5 · critical and generic groups',39)],notes:'This paper detects fingerprinting scripts, which is a different target from VPN use. We borrow the explainable scoring idea: show which inputs caused a result and test the threshold.'},
  {section:'Paper 3 · 2025 technical report',title:'A score must be checked against real examples',lead:'The report did a manual check and compared two counting methods.',points:['48 of 50 scripts flagged as invasive were confirmed manually: estimated precision 96%.','The list method found 38.55% of sites with fingerprinting scripts.','FPAnalyze found 33.57% under its own method.'],evidence:[t('tech-fpanalyze','Section 6.3 · manual check and FPAnalyze result',53),t('tech-prevalence','Section 6.1 · list-based result',50)],notes:'The percentages are about fingerprinting scripts on websites, not VPN users. The lesson for our experiment is to use labels and report errors, not only a score.'},
  {section:'Related VPN research',title:'There is direct published VPN detection work',lead:'SNITCH gives us a close server-side comparison.',points:['It combines IP geolocation, trusted landmarks and delay measurements.','It studied about 130,000 connections from more than 24,000 VPN servers and clients.','Its reported detection reached up to 93% in some regions.'],evidence:[s('snitch-abstract','SNITCH abstract · method, sample and result',1)],notes:'This is the direct VPN paper. Explain that its delay and landmark method is different from our current website, but the overall task is similar: assess VPN use from server-visible evidence. Do not use its 93% as our score.'},
  {kind:'statement',section:'Research gap + problem',title:'Can our website detect VPN-like visits with measured errors?',lead:'We will test a clear, evidence-based result on visits whose true VPN status we know.',points:['Collect trusted clues','Compare visits','Check errors'],links:[{label:'SNITCH · VPN study page 1',href:paper('snitch-madweb25.pdf',1)},{label:'NDSS · matching study page 9',href:paper('ndss2017_02B-3_Cao_paper.pdf',9)}],notes:'Our research question is whether combining the clues our website can collect gives a useful VPN assessment. Our three original papers explain browser data and scoring; SNITCH supplies a direct VPN comparison.'},
  {kind:'flow',section:'Proposed framework',title:'Our method has four steps',lead:'Each step has one job and one output.',points:['1 · Collect server and browser observations.','2 · Build and compare a device fingerprint.','3 · Score network clues and explain the result.','4 · Train and test a model on labelled visits.'],links:[{label:'Browser attributes · Beauty page 4',href:paper('beauty-sp16.pdf',4)},{label:'Device comparison · NDSS page 2',href:paper('ndss2017_02B-3_Cao_paper.pdf',2)},{label:'VPN assessment · SNITCH page 1',href:paper('snitch-madweb25.pdf',1)}],notes:'Walk through the pipeline from one visit to a result. Steps 1 to 3 are in the prototype. Step 4 is the next experiment.'},
  {section:'Step 1 · Collect',title:'Record what each side can really see',lead:'We keep the server observation separate from browser values.',points:['Server: incoming public IP, network class and optional route checks.','Browser: OS, display, canvas, WebGL and available capabilities.','Store missing values as missing, not as a VPN warning.'],evidence:[b('beauty-table','Table I · HTTP and JavaScript sources',4)],notes:'The server-observed IP is the trusted route to our site. The browser collects environment details after consent. If a privacy setting hides a value, we mark it unavailable.'},
  {section:'Step 2 · Compare',title:'Build a fingerprint, then compare visits',lead:'A fingerprint helps answer “does this look like the same device?”',points:['Clean the fields, put them in a fixed order and hash them.','Compare fields that are available in both visits.','Give stable device fields more influence than easily changed fields.'],evidence:[n('ndss-browser-factor','Browser output and device output can differ',2),n('ndss-variation','Even selected features can change',9)],notes:'Our current code makes browser and coarse-device signatures. Similarity is a weighted average over available components. The weights are starting choices based on stability; their exact numbers need labelled pair testing.'},
  {section:'Step 3 · Assess',title:'Check the network, then explain the flag',lead:'A device match adds context; routing clues drive the VPN assessment.',points:['Strong clues: known VPN or Tor network; a trusted route mismatch.','Context: location, timezone or the same device after an IP change.','Show the clues and say “unknown” when evidence is too thin.'],evidence:[s('snitch-abstract','Server-side VPN evidence is a published approach',1)],notes:'Our current code groups network, path, location, history and integrity clues. Explain that a timezone mismatch or unchanged device alone does not establish VPN use. Current numeric weights and probabilities are provisional.'},
  {section:'Next experiment · Model choice',title:'Start with simple models we can explain',lead:'Published tunnel research compared several learning methods.',points:['First baseline: logistic regression on the site’s stored fields.','Next: random forest for useful combinations of fields.','Test a neural net later if we collect enough suitable data and it improves unseen-case results.'],evidence:[m('tunnel-model-table','Table 5 · published comparison includes these models',5)],notes:'Mazel and colleagues compare logistic regression, random forest, gradient boosting and others for tunnel detection. They use packet-flow metadata. Our website has a smaller table of visit-level fields, so we must train and compare on our own data. Random forest is a sensible first non-linear option; a neural net is a later experiment.'},
  {kind:'flow',section:'Next experiment · Data',title:'Collect labelled visits before training',lead:'Every sample needs a known answer and the same set of feature fields.',points:['Record VPN off and VPN on for several providers and servers.','Also record ordinary Wi-Fi changes, mobile networks, proxy and Tor.','Repeat on different devices and browsers over time.','Label the true connection state during collection.'],links:[{label:'SNITCH · measurement design page 1',href:paper('snitch-madweb25.pdf',1)},{label:'Tunnel ML · datasets page 5',href:paper('tunnel-ml-2022.pdf',5)}],notes:'The label comes from the test setup, not from the detector’s own score. Include normal events that could otherwise look suspicious. Several devices, networks and providers keep the dataset from being too easy.'},
  {kind:'flow',section:'Next experiment · Training',title:'Train, test, then choose the model',lead:'A model is useful only if it works on visits it has never seen.',points:['Split by device and VPN provider before training.','Train the current rules, logistic regression and random forest.','Compare false alarms, recall, precision and calibrated probabilities.','Keep an “unknown” result when key signals are missing.'],links:[{label:'Tunnel ML · model comparison page 5',href:paper('tunnel-ml-2022.pdf',5)},{label:'Technical report · manual validation page 53',href:paper('techreport-2025-3.pdf',53)}],notes:'Do not let repeat visits from the same device appear in both training and testing. The current rule score is the baseline. We will choose a learned model only if it improves held-out performance and remains understandable.'},
  {kind:'final',section:'Conclusion + project status',title:'What we have built — and what comes next',lead:'vpn-detector-final is our working, consent-based research website.',points:['Built: browser, rendering and server-network collection.','Built: device comparison and explained VPN evidence.','Built: saved observations and evaluation summaries.','Next: labelled dataset, model comparison and calibrated results.'],links:[{label:'Beauty · attributes page 4',href:paper('beauty-sp16.pdf',4)},{label:'NDSS · results page 9',href:paper('ndss2017_02B-3_Cao_paper.pdf',9)},{label:'SNITCH · VPN method page 1',href:paper('snitch-madweb25.pdf',1)}],notes:'End by showing what works today and what the next research result will be. We are proposing a measured comparison of rules and simple models, with a neural network only if data supports it.'},
];

function EvidencePanel({ item }: { item: Evidence }) {
  return <figure className="ms-proof"><a className="ms-proof-image" href={item.href} target="_blank" rel="noreferrer" aria-label={'Open ' + item.source + ', PDF page ' + item.page}><img src={'/evidence/' + item.image + '.png'} alt={item.caption}/></a><figcaption>{item.caption}<a href={item.href} target="_blank" rel="noreferrer">{item.source} · PDF p. {item.page} ↗</a></figcaption></figure>;
}

function OneSlide({ item, index }: { item: Item; index: number; notes?: string }) {
  const number = String(index + 1).padStart(2, '0');
  if (item.kind === 'cover') return <Slide nav={item.title} notes={item.notes} className="ms-slide ms-cover"><div className="ms-cover-inner"><div className="ms-kicker">{item.section}</div><div className="ms-orbit" aria-hidden="true"><i/><i/><i/></div><h1>VPN detection<br/><em>through evidence</em></h1><p>{item.lead}</p><div className="ms-cover-bottom"><span>{item.points[0]}</span><span>{item.points[1]}</span></div></div></Slide>;
  return <Slide nav={item.title} notes={item.notes} className={'ms-slide ' + (item.kind === 'statement' ? 'ms-statement' : '') + ' ' + (item.kind === 'final' ? 'ms-final' : '')}><div className="ms-main"><header><div className="ms-kicker"><span>{number}</span><span className="ms-kicker-dot"/>{item.section}</div><h2>{item.title}</h2><p>{item.lead}</p></header><div className={item.evidence?.length ? 'ms-layout has-evidence' : 'ms-layout'}><div className="ms-points">{item.points.map((point, i) => <div className="ms-point" key={i}><span>{String(i + 1).padStart(2, '0')}</span><p>{point}</p></div>)}</div>{item.evidence && <div className={'ms-evidence ' + (item.evidence.length > 1 ? 'multiple' : '')}>{item.evidence.map((ev, i) => <EvidencePanel key={i} item={ev}/>)}</div>}</div>{item.kind === 'final' && <div className="ms-final-banner">The next result will compare our current rules with models trained on labelled visits.</div>}{item.links && <div className="ms-extra-links">{item.links.map((link) => <a href={link.href} key={link.href} target="_blank" rel="noreferrer">{link.label} ↗</a>)}</div>}</div></Slide>;
}

export default function Home() { return <Deck>{slides.map((item, index) => <OneSlide key={index} item={item} index={index} notes={item.notes} />)}</Deck>; }
